### ISSUE TITLE
Some pages are missing their text

### ISSUE THREAD

**Issue by Epicpkmn11** [DS-Homebrew/twilight-manual#5]
Some pages don't have any text in the nintendo_NTLG-DB_001 font for some reason in the auto generated builds, this never happens when I do it myself so I'm not really sure why it happens there and I'm not sure how to fix it, so making an issue about it. I'll try look into it again at some point but nothing I've tried has fixed it so far.

Ex: The English DSi theme page in 08d3ba0 (the latest right now)
![theme1_dsi](https://user-images.githubusercontent.com/41608708/104149411-a6e51780-539b-11eb-822d-320a762cea35.gif)

**Comment by Epicpkmn11** [comment]
Fixed by 9002434ac00189e108cb43050492fb8f6b6cbec9!
Had to add `--run-all-compositor-stages-before-draw --virtual-time-budget=10000`

**Comment by Dhalian** [comment]
The problem persists, the text appears during 1 or 2 seconds and then disappears.

(Tested on Chrome for Android and Mi Browser)
